# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp implementation of dynamic programming for knapsack problem
#'
#' @param x Dataframe
#' @param W Numeric scalar
#' @return List with two elements:
#'         1. value - optimum value that can be included in the knapsack
#'         2. elements - the list of elements that can be included in the knapsack
#' @export
dynamic_knapsack_cpp <- function(x, W) {
    .Call(`_knapsack_dynamic_knapsack_cpp`, x, W)
}

